version: "3.3"

services:
    database:
        image: postgres
        container_name: database_rotas
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=rotas_user
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=rotas_db
            - PORT=5432
            - SECRET_KEY=chave_bem_secreta
            - EXPIRES_IN=16000
            - DATABASE_URL=postgres://rotas_user:123456@localhost:5432/rotas_db

        volumes:
            - pgdata:/data/postgres

    redis:
        image: redis:alpine
        container_name: redis_rotas
        ports:
            - 6379:6379

volumes:
    pgdata:
        driver: local

networks:
    default:
        driver: bridge
